[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
ndarray = "0.16.1"
num = "0.4.3"
petgraph = "0.6.5"
rayon = "1.10.0"
winnow = "0.6.20"
